-- AlterTable
ALTER TABLE `mainrole` ADD COLUMN `type` ENUM('SYSTEM', 'CUSTOM') NOT NULL DEFAULT 'SYSTEM';

-- AlterTable
ALTER TABLE `subrole` ADD COLUMN `type` ENUM('SYSTEM', 'CUSTOM') NOT NULL DEFAULT 'SYSTEM';
